version: "3.4"

networks:
  es-net:
    driver: bridge

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=shukhrat1234
    networks:
      - es-net
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data  

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.16.1
    environment:
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=shukhrat1234
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data

  dotnet6:
    build:
      context: ./
      dockerfile: Dockerfile.DotNet6
    container_name: dotnet6-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "ElasticConfiguration:Username=elastic"
      - "ElasticConfiguration:Password=shukhrat1234"
    ports:
      - "8080:80"
    networks:
      - es-net
    depends_on:
      - kibana

  dotnet5:
    build:
      context: ./
      dockerfile: Dockerfile.DotNet5
    container_name: dotnet5-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "ElasticConfiguration:Username=elastic"
      - "ElasticConfiguration:Password=shukhrat1234"
    ports:
      - "8081:80"
    networks:
      - es-net
    depends_on:
      - kibana

volumes:
  es-data:
  kibana-data:
